logging:
  level:
    root: error

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.30:1521:orcl
    username: szec_bm
    password: szecPassword

system:
  sysfile:
    enableip: 192.168.1.30