logging:
  level:
    root: error

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@172.30.36.217:1521:orcl
    username: szec_secret
    password: szec368863

system:
  sysfile:
    enableip: 172.30.26.218