logging:
  level:
    root: info
    org.springframework: error
    com.sn.framework: debug
    # 日志输出hibernate执行语句的参数值
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

sn:
  shiro:
# session超时时间（单位：秒）
    session-timeout: 90000
    loginCaptcha: false

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.1.30:1521:orcl
    username: szec_bm
    password: szecPassword

system:
  sysfile:
    enableip: 192.168.1.30