/* S_专家评审方案模块 */
--专家评审方案
ALTER TABLE CS_EXPERT_REVIEW
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_EXPERT_REVIEW CASCADE CONSTRAINTS;

--专家抽取条件
ALTER TABLE CS_EXPERT_CONDITION
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_EXPERT_CONDITION CASCADE CONSTRAINTS;

--专家随机选择
ALTER TABLE CS_EXPERT_SELECTED
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_EXPERT_SELECTED CASCADE CONSTRAINTS;
/* E_专家评审方案模块 */


/* S_协审模块 */
--协审计划表
ALTER TABLE CS_AS_PLAN
 DROP PRIMARY KEY CASCADE;
DROP TABLE CS_AS_PLAN CASCADE CONSTRAINTS;


--协审项目
ALTER TABLE CS_AS_PLANSIGN
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_AS_PLANSIGN CASCADE CONSTRAINTS;


--协审计划项目管理表
DROP TABLE CS_AS_PLAN_CS_AS_PLANSIGN CASCADE CONSTRAINTS;


--协审计划协审单位
DROP TABLE CS_AS_PLAN_CS_AS_UNIT CASCADE CONSTRAINTS;
/* S_协审模块 */


/* S_项目模块 */
--项目关联
ALTER TABLE CS_ASSOCIATE_SIGN
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_ASSOCIATE_SIGN CASCADE CONSTRAINTS;

--发文
ALTER TABLE CS_DISPATCH_DOC
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_DISPATCH_DOC CASCADE CONSTRAINTS;


--合并发文（旧）
ALTER TABLE CS_MERGE_DISPA
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_MERGE_DISPA CASCADE CONSTRAINTS;

--合并项
ALTER TABLE CS_MERGE_OPTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_MERGE_OPTION CASCADE CONSTRAINTS;

--合并发文（新）
ALTER TABLE CS_SIGN_MERGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SIGN_MERGE CASCADE CONSTRAINTS;

--归档信息
ALTER TABLE CS_FILE_RECORD
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_FILE_RECORD CASCADE CONSTRAINTS;


--工作方案
ALTER TABLE CS_WORK_PROGRAM
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_WORK_PROGRAM CASCADE CONSTRAINTS;

--收文负责人
ALTER TABLE CS_SIGN_PRINCIPAL
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SIGN_PRINCIPAL CASCADE CONSTRAINTS;

--收文负责人
ALTER TABLE CS_SIGN_PRINCIPAL2
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SIGN_PRINCIPAL2 CASCADE CONSTRAINTS;

--收文分支
ALTER TABLE CS_SIGN_BRANCH
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SIGN_BRANCH CASCADE CONSTRAINTS;

--项目补充资料函
ALTER TABLE CS_ADD_REGISTERFILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_ADD_REGISTERFILE CASCADE CONSTRAINTS;

--项目补充资料文件
ALTER TABLE CS_ADD_SUPPLETTER
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_ADD_SUPPLETTER CASCADE CONSTRAINTS;

--项目暂停
ALTER TABLE CS_PROJECTSTOP
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_PROJECTSTOP CASCADE CONSTRAINTS;

--收文
ALTER TABLE CS_SIGN
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SIGN CASCADE CONSTRAINTS;
/* E_项目模块 */


/* S_会议室模块 */
--会议室
ALTER TABLE CS_MEETING_ROOM
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_MEETING_ROOM CASCADE CONSTRAINTS;

--会议室预定
ALTER TABLE CS_ROOM_BOOKING
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_ROOM_BOOKING CASCADE CONSTRAINTS;
/* E_会议室模块 */


--附件
ALTER TABLE CS_SYSFILE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SYSFILE CASCADE CONSTRAINTS;

--文件质量库
ALTER TABLE CS_FILELIBRARY
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_FILELIBRARY CASCADE CONSTRAINTS;

--财务管理
ALTER TABLE cs_financial_manager
 DROP PRIMARY KEY CASCADE;

DROP TABLE cs_financial_manager CASCADE CONSTRAINTS;

--审批意见
ALTER TABLE CS_IDEA
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_IDEA CASCADE CONSTRAINTS;

--节假日管理
ALTER TABLE CS_WORKDAY
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_WORKDAY CASCADE CONSTRAINTS;

--通知公告
ALTER TABLE CS_ANNOUNTMENT
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_ANNOUNTMENT CASCADE CONSTRAINTS;

/* S_共享文件模块 */
--共享文件
ALTER TABLE CS_SHARING_PLATFORM
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SHARING_PLATFORM CASCADE CONSTRAINTS;

--共享文件权限
ALTER TABLE CS_SHARING_PRIVILEGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE CS_SHARING_PRIVILEGE CASCADE CONSTRAINTS;
/* E_共享文件模块 */

--清除流程数据
delete from ACT_GE_BYTEARRAY;
delete from ACT_HI_ACTINST;
delete from ACT_HI_COMMENT;
delete from ACT_HI_IDENTITYLINK;
delete from ACT_HI_PROCINST;
delete from ACT_HI_TASKINST;
delete from ACT_HI_VARINST;
delete from ACT_RE_DEPLOYMENT;

delete from ACT_RU_IDENTITYLINK;
delete from ACT_RU_JOB;
delete from ACT_RU_TASK;
delete from ACT_RU_VARIABLE;
delete from ACT_RE_PROCDEF;
delete from ACT_RU_EXECUTION;